= Auxly

image:http://img.shields.io/:license-mit-blue.svg["License", link="https://github.com/jeffrimko/Auxly/blob/master/LICENSE"]
image:https://travis-ci.org/jeffrimko/Auxly.svg?branch=master["Build Status"]

== Introduction
This project provides a Python 2.7/3.x library for common tasks especially when writing shell-like scripts. Some of the functionality overlaps with the standard library but the API is slightly modified.

The goal of this project is to leverage the straightforward, clean syntax of Python while avoiding some of the boilerplate code that might be necessary when using the standard library.

== Status
Currently, this project is in the **development release** stage. While this project is suitable for use, please note that there may be incompatibilities in new releases.

Release notes are maintained in the project https://github.com/jeffrimko/Auxly/blob/master/CHANGELOG.adoc[changelog].

== Requirements
Auxly should run on any Python 2.7/3.x interpreter without additional dependencies.

== Installation
Auxly can be installed with pip using the following command: `pip install auxly`

Additionally, Auxly can be installed from source by running: `python setup.py install`

== Documentation
The full documentation for this project can be found http://auxly.readthedocs.io[here on Read the Docs].

== Similar
The following projects are similar and may be worth checking out:

  - https://github.com/cdgriffith/Reusables[Reusables]
